<!-- LAYER NR. 12 -->
<div class="tp-caption   tp-resizeme" id="slide-145-layer-17" data-x="['center','center','center','center']" data-hoffset="['0','0','3','0']" data-y="['top','top','top','top']" data-voffset="['122','252','212','147']" data-fontsize="['40','45','36','36']" data-lineheight="['50','50','40','40']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"
     style="z-index: 8; white-space: nowrap; font-size: 40px; line-height: 50px; font-weight: 800; color: rgba(255,255,255,1);font-family:Open Sans;">PROMOÇÃO
</div>

<!-- LAYER NR. 13 -->
<div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-145-layer-18" data-x="['center','center','center','center']" data-hoffset="['-3','0','-2','0']" data-y="['top','top','top','top']" data-voffset="['24','136','95','44']" data-width="259" data-height="85" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9;font-family:Open Sans;background-color:rgba(255,255,255,1);"> </div>

<!-- LAYER NR. 14 -->
<div class="tp-caption   tp-resizeme" id="slide-145-layer-19" data-x="['center','center','center','center']" data-hoffset="['-5','0','-6','0']" data-y="['top','top','top','top']" data-voffset="['48','163','118','74']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10; white-space: nowrap; font-size: 40px; line-height: 54px; font-weight: 800; color: rgba(211,80,36,1);font-family:Open Sans;">-30% OFF </div>

<!-- LAYER NR. 15 -->
<div class="tp-caption   tp-resizeme" id="slide-145-layer-21" data-x="['center','center','center','center']" data-hoffset="['-5','0','-6','0']" data-y="['top','top','top','top']" data-voffset="['32','143','105','49']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11; white-space: nowrap; font-size: 12px; line-height: 22px; font-weight: 700; color: rgba(30,30,30,1);font-family:Open Sans;">SÓ ESTA SEMANA </div>

<!-- LAYER NR. 16 -->
<div class="tp-caption rev-btn " id="slide-145-layer-23" data-x="['center','center','center','center']" data-hoffset="['0','0','-2','-2']" data-y="['top','top','middle','middle']" data-voffset="['246','383','-34','-34']" data-fontsize="['13','14','13','13']" data-lineheight="['12','16','12','12']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,1);bg:rgba(255,255,255,1);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[25,25,25,25]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[25,25,25,25]" style="z-index: 12; white-space: nowrap; font-size: 13px; line-height: 12px; font-weight: 600; color: rgba(255,255,255,1);font-family:Hind;background-color:rgba(0,0,0,1);border-color:rgba(0,0,0,1);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">VER DETALHES </div>

<!-- LAYER NR. 17 -->
<div class="tp-caption   tp-resizeme" id="slide-145-layer-25" data-x="['center','center','center','center']" data-hoffset="['0','0','-3','0']" data-y="['top','top','top','top']" data-voffset="['180','314','263','191']" data-fontsize="['14','16','14','13']" data-lineheight="['22','24','22','22']" data-width="['402','478','402','402']" data-height="['45','46','45','45']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13; min-width: 402px; max-width: 402px; max-width: 45px; max-width: 45px; white-space: normal; font-size: 14px; line-height: 22px; font-weight: 400; color: rgba(255,255,255,1);font-family:Hind;">Texto slider 2 aqui... </div>
